-- ==============================================================================
-- Config: Commercial Business Empire (standalone_business_empire)
-- Generated by FiveM Standalone Script Factory
-- ==============================================================================
Config = {}

Config.SystemLabel = "Commercial Business Empire"
Config.Framework = "auto" -- auto, ox, qb, esx, standalone
Config.EnableNUI = true
Config.EnableSupplies = true
Config.EnableVaultHeists = true
Config.EnableGuards = true
Config.EnableMissions = true
Config.EnableNPCStreetSales = true
Config.EnableCustomLiveries = true

-- Payout & Economy
Config.BasePayout = 350
Config.PayoutIntervalSeconds = 60
Config.RepGainIntervalSeconds = 300
Config.SupplyDecayPerPayout = 4

Config.Zones = {
    ["zone_01"] = {
        label = "Commercial Business Empire Hub",
        coords = vec3(149.95, -1040.59, 29.37),
        radius = 20.0,
        payout = 400
    }
}
