-- ========================================================
-- SUPABASE SCHEMA FOR CUSTOM LOBBIES MATCHMAKING PORTAL
-- ========================================================
-- Execute this script inside your Supabase project's SQL Editor:
-- Dashboard -> SQL Editor -> New Query -> Run

-- 1. Create Players Profile Table
CREATE TABLE IF NOT EXISTS public.players (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  avatar TEXT DEFAULT '👤',
  bio TEXT DEFAULT 'Competitive Custom Lobbies player.',
  steam_hex TEXT,
  role TEXT DEFAULT 'Flex',
  color TEXT DEFAULT '#7c3aed',
  referrals_count INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Game Stats Table (Linked to Players)
CREATE TABLE IF NOT EXISTS public.game_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id UUID REFERENCES public.players(id) ON DELETE CASCADE NOT NULL,
  game TEXT NOT NULL,
  elo INT DEFAULT 1000 NOT NULL,
  wins INT DEFAULT 0 NOT NULL,
  losses INT DEFAULT 0 NOT NULL,
  kd_ratio NUMERIC(4,2) DEFAULT 1.00 NOT NULL,
  elo_history INT[] DEFAULT ARRAY[1000]::INT[] NOT NULL,
  UNIQUE (player_id, game)
);

-- 3. Create Referrals Log Table
CREATE TABLE IF NOT EXISTS public.referrals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referrer_id UUID REFERENCES public.players(id) ON DELETE CASCADE,
  referred_player_id UUID REFERENCES public.players(id) ON DELETE CASCADE,
  code_used TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.game_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS Policies
-- Allow anyone to read profiles and leaderboard stats
CREATE POLICY "Allow public read access to players" ON public.players
  FOR SELECT USING (true);

CREATE POLICY "Allow public read access to game_stats" ON public.game_stats
  FOR SELECT USING (true);

-- Allow authenticated users to update ONLY their own profile and stats
CREATE POLICY "Allow individual update of own profile" ON public.players
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Allow individual update of own game_stats" ON public.game_stats
  FOR UPDATE USING (auth.uid() = player_id);

-- 6. Trigger to automatically generate Player profile on Supabase Auth SignUp
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.players (id, username, avatar)
  VALUES (
    new.id,
    COALESCE(split_part(new.email, '@', 1), 'Gamer_' || substr(new.id::text, 1, 6)),
    '👤'
  );
  
  -- Initialize stats for all three games
  INSERT INTO public.game_stats (player_id, game) VALUES (new.id, 'arkheron');
  INSERT INTO public.game_stats (player_id, game) VALUES (new.id, 'hockey');
  INSERT INTO public.game_stats (player_id, game) VALUES (new.id, 'zealot');
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger execution link
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
