-- ==============================================================================
-- Resource: tripo_rosin_press
-- Generated by FiveM 3D Asset Studio (Tripo2FiveM Pipeline)
-- ==============================================================================

local spawnedObject = nil

-- Spawn 3D World Prop with Collision
CreateThread(function()
    local modelHash = GetHashKey(Config.PropModel or 'prop_weed_press_01')
    RequestModel(modelHash)
    while not HasModelLoaded(modelHash) do Wait(10) end

    local coords = Config.SpawnCoords or vec4(149.95, -1040.59, 29.37, 90)
    spawnedObject = CreateObject(modelHash, coords.x, coords.y, coords.z - 1.0, false, false, false)
    SetEntityHeading(spawnedObject, coords.w)
    FreezeEntityPosition(spawnedObject, true)
    SetEntityAsMissionEntity(spawnedObject, true, true)

    -- Register Target Interaction
    if Config.Framework == 'ox_target' or exports['ox_target'] then
        exports.ox_target:addLocalEntity(spawnedObject, {
            {
                name = 'tripo_rosin_press_interact',
                icon = 'fa-solid fa-cube',
                label = 'Press Rosin Extract',
                onSelect = function()
                    TriggerEvent('tripo_rosin_press:client:startAction')
                end
            }
        })
    elseif exports['qb-target'] then
        exports['qb-target']:AddTargetEntity(spawnedObject, {
            options = {
                {
                    icon = 'fa-solid fa-cube',
                    label = 'Press Rosin Extract',
                    action = function()
                        TriggerEvent('tripo_rosin_press:client:startAction')
                    end
                }
            },
            distance = 2.5
        })
    end
end)

-- Action Execution Event Handler
RegisterNetEvent('tripo_rosin_press:client:startAction', function()
    local ped = PlayerPedId()

    -- Progress Bar
    if lib and lib.progressBar then
        local success = lib.progressBar({
            duration = 6000,
            label = 'Press Rosin Extract...',
            useWhileDead = false,
            canCancel = true,
            disable = { car = true, move = true, combat = true },
            anim = {
                dict = 'anim@amb@business@weed@weed_inspecting_high_p1@',
                clip = 'idle'
            }
        })
        if success then
            TriggerServerEvent('tripo_rosin_press:server:completeAction')
        end
    else
        TaskPlayAnim(ped, 'anim@amb@business@weed@weed_inspecting_high_p1@', 'idle', 8.0, -8.0, 6000, 49, 0, false, false, false)
        Wait(6000)
        ClearPedTasks(ped)
        TriggerServerEvent('tripo_rosin_press:server:completeAction')
    end
end)
