/**
 * HELIX Platform - Pacifica Gang Territory & Dynamic Turf War System
 * Divides Pacifica into conquerable gang zones with economic perks, hourly protection taxes, and incursion alerts.
 */

Helix.server(async () => {
  console.log('[TURF WARS] Initializing Gang Territory & Zone Conquest System...');

  const TURF_DISTRICTS = new Map([
    ['downtown_finance', {
      id: 'downtown_finance',
      name: 'Downtown Financial Hub',
      controllingGang: 'Syndicate 8',
      influencePct: 78,
      hourlyTaxRevenue: 4500,
      perkDescription: '+30% Money Laundering Rate & Luxury Contraband Client Demand',
      color: '#3b82f6',
      capturePointCoords: { x: 150.0, y: 400.0, z: 12.0 },
      underAttack: false
    }],
    ['industrial_docks', {
      id: 'industrial_docks',
      name: 'Pacific Maritime Docks',
      controllingGang: 'Harbor Cartel',
      influencePct: 92,
      hourlyTaxRevenue: 6200,
      perkDescription: '+50% Maritime Export Payouts & -25% Chemical Precursor Bulk Costs',
      color: '#10b981',
      capturePointCoords: { x: 950.0, y: -500.0, z: 4.0 },
      underAttack: false
    }],
    ['neon_strip', {
      id: 'neon_strip',
      name: 'Neon Boulevard & Nightclubs',
      controllingGang: 'Viper Triad',
      influencePct: 65,
      hourlyTaxRevenue: 5100,
      perkDescription: '+40% Nightclub Ecstasy/Coke/Weed Sales Volume & Fast Dealer Cooldowns',
      color: '#ec4899',
      capturePointCoords: { x: -300.0, y: -200.0, z: 8.0 },
      underAttack: false
    }],
    ['outskirts_badlands', {
      id: 'outskirts_badlands',
      name: 'Outskirts Desert Badlands',
      controllingGang: 'Ghost Nomads',
      influencePct: 84,
      hourlyTaxRevenue: 2800,
      perkDescription: '0% Police Helicopter Surveillance & Open Sandbox Compound Building',
      color: '#f59e0b',
      capturePointCoords: { x: -750.0, y: 900.0, z: 30.0 },
      underAttack: false
    }]
  ]);

  // Player Gang Registrations
  const PlayerGangs = new Map();

  // --- Endpoints ---

  Helix.endpoint('getTurfMapState', async () => {
    return { success: true, turfs: Array.from(TURF_DISTRICTS.values()) };
  });

  Helix.endpoint('captureTurfPoint', async (playerId, data) => {
    const { districtId, gangName } = data || {};
    const turf = TURF_DISTRICTS.get(districtId);
    if (!turf) return { success: false, message: 'Invalid turf zone' };

    const claimingGang = gangName || `Crew_${playerId}`;
    const previousGang = turf.controllingGang;

    turf.controllingGang = claimingGang;
    turf.influencePct = 100;
    turf.underAttack = false;

    console.log(`[TURF WAR] 🚩 ${claimingGang} has captured ${turf.name} (previously held by ${previousGang})!`);
    Helix.emit('turfCapturedBroadcast', {
      districtId,
      districtName: turf.name,
      newGang: claimingGang,
      previousGang
    });

    return {
      success: true,
      message: `Zone captured! ${turf.name} is now under ${claimingGang} control.`,
      turf
    };
  });

  Helix.endpoint('triggerTurfIncursion', async (playerId, data) => {
    const { districtId, attackingGang } = data || {};
    const turf = TURF_DISTRICTS.get(districtId);
    if (!turf) return { success: false, message: 'Invalid turf zone' };

    turf.underAttack = true;
    console.warn(`[TURF ALARM] ⚠️ ${turf.name} is UNDER ATTACK by ${attackingGang || 'Rivals'}!`);
    Helix.emit('turfAlarmAlert', {
      districtId,
      districtName: turf.name,
      controllingGang: turf.controllingGang
    });

    return { success: true, message: `Incursion triggered on ${turf.name}!` };
  });

  // Hourly Turf Revenue Distribution Loop (Simulated 30-sec ticks for testing)
  setInterval(() => {
    TURF_DISTRICTS.forEach(turf => {
      console.log(`[TURF DIVIDEND] $${turf.hourlyTaxRevenue.toLocaleString()} protection tax generated by ${turf.name} for ${turf.controllingGang}`);
      Helix.emit('turfDividendPaid', {
        gang: turf.controllingGang,
        amount: turf.hourlyTaxRevenue,
        district: turf.name
      });
    });
  }, 30000);

  global.TurfWarsEngine = {
    TURF_DISTRICTS,
    PlayerGangs
  };
});
