--[[
    City Underground - Shared Base Building, Fortifications & Prop Defenses
    Defines structural pieces, defense barricades, keypad security doors, sentry alarms, and health pools.
--]]

CityUnderground = CityUnderground or {}
CityUnderground.BaseBuilder = CityUnderground.BaseBuilder or {}
CityUnderground.BaseBuilder.Catalog = CityUnderground.BaseBuilder.Catalog or {}

CityUnderground.BaseBuilder.Categories = {
    ["barricades"] = { name = "Flippable Barricades & Door Stops", icon = "🛑" },
    ["suburban"] = { name = "Suburban Warfare & Lawn Traps", icon = "🏡" },
    ["defense"] = { name = "Defenses & Fortifications", icon = "🛡️" },
    ["structure"] = { name = "Walls & Floors", icon = "🧱" },
    ["furniture"] = { name = "Living & Comfort", icon = "🛋️" },
    ["kitchen"] = { name = "Kitchen & Food", icon = "🍳" },
    ["production"] = { name = "Crafting & Botany", icon = "🧪" },
    ["security"] = { name = "Storage & Security", icon = "🔒" },
    ["lighting"] = { name = "Decor & Lighting", icon = "💡" }
}

-- Furniture & Prop Defense Catalog Definition
CityUnderground.BaseBuilder.Catalog = {
    -- Flippable Barricades & Anti-Lockpick Defenses
    ["barricade_flippable_bookshelf"] = {
        name = "Heavy Oak Bookshelf (Stand-Up Barricade)",
        category = "barricades",
        price = 380,
        width = 2, height = 1,
        icon = "📚",
        model = "models/props/bookshelf_barricade.mdl",
        color = "#78350f",
        maxHealth = 1500,
        isDefense = true,
        isFlippable = true,
        isMovable = true,
        isInteractive = true,
        action = "FLIP_STAND",
        description = "Solid oak bookshelf that can be tipped and stood upright to instantly wedge hallway chokepoints shut."
    },
    ["barricade_flippable_table"] = {
        name = "Steel-Reinforced Table (Flip Gun-Shield)",
        category = "barricades",
        price = 320,
        width = 3, height = 2,
        icon = "🪑",
        model = "models/props/table_barricade.mdl",
        color = "#451a03",
        maxHealth = 1100,
        isDefense = true,
        isFlippable = true,
        isMovable = true,
        isInteractive = true,
        action = "FLIP_TABLE",
        description = "Dining table that flips on its side to create a ballistic firing bunker with peep-holes."
    },
    ["barricade_heavy_wardrobe"] = {
        name = "Sliding Armoire Doorway Blockade",
        category = "barricades",
        price = 550,
        width = 2, height = 2,
        icon = "🚪",
        model = "models/props/heavy_armoire.mdl",
        color = "#292524",
        maxHealth = 1800,
        isDefense = true,
        isMovable = true,
        isInteractive = true,
        action = "SHOVE_BARRICADE",
        description = "Massive steel-lined wardrobe on caster glides that can be shoved directly against picked doors."
    },
    ["defense_door_wedge"] = {
        name = "Titanium Door Jammer Wedge",
        category = "barricades",
        price = 140,
        width = 1, height = 1,
        icon = "🛑",
        model = "models/props/door_wedge.mdl",
        color = "#0284c7",
        maxHealth = 1200,
        isDefense = true,
        isInteractive = true,
        action = "JAM_DOOR",
        description = "High-friction alloy wedge kicked under doors to prevent lockpicked doors from swinging open."
    },
    ["defense_lock_electrifier"] = {
        name = "Anti-Lockpick Handle Stun Rig",
        category = "barricades",
        price = 480,
        width = 1, height = 1,
        icon = "⚡",
        model = "models/props/lock_stun_rig.mdl",
        color = "#eab308",
        maxHealth = 250,
        isDefense = true,
        shocksLockpickers = true,
        isInteractive = true,
        action = "TEST_STUN_RIG",
        description = "Electro-shock capacitor attached to door handles that delivers 10,000V to lockpickers and snaps their picks."
    },
    ["defense_door_flashbang_trip"] = {
        name = "Door-Mounted Flashbang Rig",
        category = "barricades",
        price = 290,
        width = 1, height = 1,
        icon = "💥",
        model = "models/props/flashbang_rig.mdl",
        color = "#f97316",
        maxHealth = 180,
        isDefense = true,
        isInteractive = true,
        action = "TEST_FLASH_RIG",
        description = "Mechanical trip trigger that detonates a blinding flashbang directly into the eyes of lockpicking intruders."
    },
    ["defense_falling_cabinet_trap"] = {
        name = "Tilted Filing Cabinet Drop-Trap",
        category = "barricades",
        price = 410,
        width = 2, height = 1,
        icon = "🗄️",
        model = "models/props/tilted_cabinet.mdl",
        color = "#475569",
        maxHealth = 600,
        isDefense = true,
        crushesIntruders = true,
        isInteractive = true,
        action = "TEST_DROP_TRAP",
        description = "Tilted steel cabinet mounted over doorways that crashes down onto raiders when the door swings inward."
    },
    ["furniture_cast_iron_stove_blocker"] = {
        name = "Cast-Iron Stove Doorway Anchor",
        category = "barricades",
        price = 620,
        width = 2, height = 2,
        icon = "🍳",
        model = "models/props/heavy_stove.mdl",
        color = "#1e293b",
        maxHealth = 2200,
        isDefense = true,
        isMovable = true,
        isInteractive = true,
        action = "SHOVE_BARRICADE",
        description = "500-pound commercial cast-iron stove shoved in front of entrances as an impenetrable physical anchor."
    },
    -- Suburban Warfare & Lawn Traps
    ["suburban_claymore_gnome"] = {
        name = "Tactical Claymore Lawn Gnome",
        category = "suburban",
        price = 320,
        width = 1, height = 1,
        icon = "🧙‍♂️",
        model = "models/props/claymore_gnome.mdl",
        color = "#e11d48",
        maxHealth = 120,
        isDefense = true,
        damageIntruders = true,
        blastDamage = 95,
        blastRadius = 3.5,
        isInteractive = true,
        action = "TEST_GNOME",
        description = "Inconspicuous ceramic lawn gnome packed with directional blast powder."
    },
    ["suburban_chem_sprinkler"] = {
        name = "High-Pressure Pepper Sprinkler",
        category = "suburban",
        price = 450,
        width = 1, height = 1,
        icon = "💦",
        model = "models/props/yard_sprinkler.mdl",
        color = "#06b6d4",
        maxHealth = 250,
        isDefense = true,
        damageIntruders = true,
        spraysChemicals = true,
        isInteractive = true,
        action = "TEST_SPRINKLER",
        description = "Pressurized lawn sprinkler connected to caustic tear-gas solution tanks."
    },
    ["suburban_firework_mortar"] = {
        name = "Tripwire Mortar Box (Fireworks)",
        category = "suburban",
        price = 550,
        width = 1, height = 1,
        icon = "🎆",
        model = "models/props/firework_box.mdl",
        color = "#f59e0b",
        maxHealth = 300,
        isDefense = true,
        isInteractive = true,
        action = "TEST_FIREWORKS",
        description = "Automated mortar battery discharging blinding screaming pyrotechnics at intruders."
    },
    ["suburban_electric_gate"] = {
        name = "High-Voltage Electrified Gate",
        category = "suburban",
        price = 680,
        width = 2, height: 1,
        icon = "⚡",
        model = "models/props/electric_picket_gate.mdl",
        color = "#eab308",
        maxHealth = 700,
        isDefense = true,
        shocksTrespassers = true,
        shockVoltage = 5000,
        isInteractive = true,
        action = "TOGGLE_VOLTAGE",
        description = "Suburban picket gate energized by 5,000V capacitor shock circuit."
    },
    ["suburban_oil_slick"] = {
        name = "Driveway Grease & Oil Dispenser",
        category = "suburban",
        price = 280,
        width = 2, height = 1,
        icon = "🛢️",
        model = "models/props/oil_dispenser.mdl",
        color = "#18181b",
        maxHealth = 200,
        isDefense = true,
        causesSlipping = true,
        isInteractive = true,
        action = "DISPENSE_OIL",
        description = "Discharges slick industrial lubricant causing intruders to slip and ragdoll."
    },
    ["suburban_caltrop_spikes"] = {
        name = "Concealed Lawn Spike Strip",
        category = "suburban",
        price = 190,
        width = 2, height = 1,
        icon = "📍",
        model = "models/props/caltrop_strip.mdl",
        color = "#71717a",
        maxHealth = 150,
        isDefense = true,
        popsTires = true,
        slowsMovement = true,
        description = "Sharp tire-puncturing steel caltrops concealed in lawn turf."
    },
    ["suburban_mailbox_alarm"] = {
        name = "Tactical Booby-Trapped Mailbox",
        category = "suburban",
        price = 260,
        width = 1, height = 1,
        icon = "📬",
        model = "models/props/suburban_mailbox.mdl",
        color = "#3b82f6",
        maxHealth = 200,
        isDefense = true,
        triggersSiren = true,
        notifies911 = true,
        isInteractive = true,
        action = "TEST_MAILBOX",
        description = "Tamper-evident mailbox with ear-piercing siren and automatic 911 dispatch."
    },
    ["suburban_porch_bunker"] = {
        name = "Sandbag Porch Bunker (\"NO TRESPASSING\")",
        category = "suburban",
        price = 390,
        width = 2, height = 1,
        icon = "🏖️",
        model = "models/props/porch_sandbag_bunker.mdl",
        color = "#854d0e",
        maxHealth = 950,
        isDefense = true,
        providesCover = true,
        description = "Reinforced residential porch bunker with American flag and heavy ballistic shielding."
    },
    ["suburban_pepperball_sentry"] = {
        name = "Automated Pepperball Sentry Turret",
        category = "suburban",
        price = 1400,
        width = 1, height = 1,
        icon = "🤖",
        model = "models/props/sentry_turret.mdl",
        color = "#dc2626",
        maxHealth = 450,
        isDefense = true,
        autoTargetIntruders = true,
        isInteractive = true,
        action = "TEST_SENTRY",
        description = "Tripod-mounted motion tracking turret firing rapid non-lethal pepperballs."
    },
    ["suburban_megaphone_pa"] = {
        name = "Rooftop Megaphone PA (\"GET OFF MY LAWN!\")",
        category = "suburban",
        price = 420,
        width = 1, height = 1,
        icon = "📢",
        model = "models/props/megaphone_horn.mdl",
        color = "#fbbf24",
        maxHealth = 200,
        isDefense = true,
        broadcastsWarning = true,
        isInteractive = true,
        action = "BROADCAST_MEGAPHONE",
        description = "High-decibel PA speaker system that blasts defense voice warnings across the block."
    },
    ["suburban_strobe_floodlight"] = {
        name = "50,000 Lumen Strobe Spotlight",
        category = "suburban",
        price = 340,
        width = 1, height = 1,
        icon = "🔦",
        model = "models/props/strobe_spotlight.mdl",
        color = "#fef08a",
        maxHealth = 180,
        isDefense = true,
        blindsIntruders = true,
        isInteractive = true,
        action = "TEST_STROBE",
        description = "Ultra-bright strobing perimeter floodlight that blinds night raiders."
    },
    ["suburban_garage_blast_door"] = {
        name = "Reinforced Garage Blast Shutter",
        category = "suburban",
        price = 1600,
        width = 3, height = 1,
        icon = "🛡️",
        model = "models/props/garage_blast_shutter.mdl",
        color = "#334155",
        maxHealth = 2000,
        isDefense = true,
        isInteractive = true,
        action = "TOGGLE_SHUTTER",
        description = "Heavy motorized roll-up steel shutter for complete driveway and garage lockdown."
    },
    -- Prop Defenses & Fortifications
    ["defense_steel_barricade"] = {
        name = "Heavy Steel Blast Barricade",
        category = "defense",
        price = 450,
        width = 2, height: 1,
        icon = "🛡️",
        model = "models/props/steel_barricade.mdl",
        color = "#475569",
        maxHealth = 800,
        isDefense = true
    },
    ["defense_keypad_door"] = {
        name = "Reinforced Keypad Security Door",
        category = "defense",
        price = 1200,
        width = 2, height: 1,
        icon = "🚪",
        model = "models/props/security_door.mdl",
        color = "#1e3a8a",
        maxHealth = 1200,
        isDefense = true,
        isInteractive = true,
        action = "OPEN_KEYPAD",
        requiresPin = true
    },
    ["defense_shooting_slit"] = {
        name = "Armored Gun-Port Shooting Wall",
        category = "defense",
        price = 600,
        width = 2, height: 1,
        icon = "🎯",
        model = "models/props/gunport_wall.mdl",
        color = "#334155",
        maxHealth = 1000,
        isDefense = true
    },
    ["defense_sandbags"] = {
        name = "Military Ballistic Sandbags",
        category = "defense",
        price = 220,
        width = 2, height: 1,
        icon = "🧱",
        model = "models/props/sandbags.mdl",
        color = "#78350f",
        maxHealth = 500,
        isDefense = true
    },
    ["defense_barbed_wire"] = {
        name = "Concertina Razor Wire Strip",
        category = "defense",
        price = 180,
        width = 2, height: 1,
        icon = "⛓️",
        model = "models/props/barbed_wire.mdl",
        color = "#94a3b8",
        maxHealth = 350,
        isDefense = true,
        damageIntruders = true,
        slowsMovement = true
    },
    ["defense_tripwire_alarm"] = {
        name = "Laser Motion Tripwire Alarm",
        category = "defense",
        price = 380,
        width = 1, height: 1,
        icon = "🚨",
        model = "models/props/laser_sensor.mdl",
        color = "#ef4444",
        maxHealth = 150,
        isDefense = true,
        isInteractive = true,
        action = "TOGGLE_ALARM"
    },
    ["defense_riot_grate"] = {
        name = "Heavy Steel Riot Security Grate",
        category = "defense",
        price = 700,
        width = 2, height: 1,
        icon = "🔒",
        model = "models/props/security_grate.mdl",
        color = "#0f172a",
        maxHealth = 900,
        isDefense = true,
        isInteractive = true,
        action = "TOGGLE_GRATE"
    },

    -- Structures & Fortnite Fast-Build Pieces
    ["wall_fortnite_wood"] = {
        name = "Wood Wall (Fortnite)",
        category = "structure",
        price = 25,
        width = 1, height = 1,
        icon = "🧱",
        model = "models/props/fortnite_wall_wood.mdl",
        color = "#92400e",
        maxHealth = 150
    },
    ["wall_fortnite_brick"] = {
        name = "Brick Wall (Fortnite)",
        category = "structure",
        price = 45,
        width = 1, height = 1,
        icon = "🧱",
        model = "models/props/fortnite_wall_brick.mdl",
        color = "#b91c1c",
        maxHealth = 300
    },
    ["wall_fortnite_metal"] = {
        name = "Metal Wall (Fortnite)",
        category = "structure",
        price = 85,
        width = 1, height = 1,
        icon = "🛡️",
        model = "models/props/fortnite_wall_metal.mdl",
        color = "#334155",
        maxHealth = 500
    },
    ["floor_fortnite_wood"] = {
        name = "Wood Floor Platform",
        category = "structure",
        price = 20,
        width = 1, height = 1,
        icon = "🪵",
        model = "models/props/fortnite_floor_wood.mdl",
        color = "#78350f",
        maxHealth = 150
    },
    ["floor_fortnite_brick"] = {
        name = "Brick Floor Platform",
        category = "structure",
        price = 35,
        width = 1, height = 1,
        icon = "⬛",
        model = "models/props/fortnite_floor_brick.mdl",
        color = "#475569",
        maxHealth = 300
    },
    ["floor_fortnite_metal"] = {
        name = "Metal Floor Platform",
        category = "structure",
        price = 65,
        width = 1, height = 1,
        icon = "🛡️",
        model = "models/props/fortnite_floor_metal.mdl",
        color = "#1e293b",
        maxHealth = 500
    },
    ["ramp_fortnite_wood"] = {
        name = "Wood Ramp / Stairs",
        category = "structure",
        price = 30,
        width = 1, height = 1,
        icon = "📐",
        model = "models/props/fortnite_ramp_wood.mdl",
        color = "#b45309",
        maxHealth = 150
    },
    ["ramp_fortnite_brick"] = {
        name = "Brick Ramp / Stairs",
        category = "structure",
        price = 50,
        width = 1, height = 1,
        icon = "📐",
        model = "models/props/fortnite_ramp_brick.mdl",
        color = "#991b1b",
        maxHealth = 300
    },
    ["ramp_fortnite_metal"] = {
        name = "Metal Ramp / Stairs",
        category = "structure",
        price = 90,
        width = 1, height = 1,
        icon = "📐",
        model = "models/props/fortnite_ramp_metal.mdl",
        color = "#0f172a",
        maxHealth = 500
    },
    ["cone_fortnite_wood"] = {
        name = "Wood Cone / Roof",
        category = "structure",
        price = 25,
        width = 1, height = 1,
        icon = "🔺",
        model = "models/props/fortnite_cone_wood.mdl",
        color = "#d97706",
        maxHealth = 150
    },
    ["cone_fortnite_brick"] = {
        name = "Brick Cone / Roof",
        category = "structure",
        price = 40,
        width = 1, height = 1,
        icon = "🔺",
        model = "models/props/fortnite_cone_brick.mdl",
        color = "#7f1d1d",
        maxHealth = 300
    },
    ["cone_fortnite_metal"] = {
        name = "Metal Cone / Roof",
        category = "structure",
        price = 75,
        width = 1, height = 1,
        icon = "🔺",
        model = "models/props/fortnite_cone_metal.mdl",
        color = "#1e293b",
        maxHealth = 500
    },
    ["wall_drywall"] = {
        name = "Reinforced Drywall Partition",
        category = "structure",
        price = 75,
        width = 1, height: 1,
        icon = "🧱",
        model = "models/props/interior_wall.mdl",
        color = "#e2e8f0"
    },
    ["wall_brick"] = {
        name = "Exposed Red Brick Wall",
        category = "structure",
        price = 120,
        width = 1, height: 1,
        icon = "🧱",
        model = "models/props/brick_wall.mdl",
        color = "#991b1b"
    },
    ["wall_glass"] = {
        name = "Modern Tinted Glass Divider",
        category = "structure",
        price = 200,
        width = 1, height: 1,
        icon = "🪟",
        model = "models/props/glass_wall.mdl",
        color = "#38bdf8"
    },
    ["floor_hardwood"] = {
        name = "Dark Oak Hardwood Flooring",
        category = "structure",
        price = 45,
        width = 1, height: 1,
        icon = "🪵",
        model = "models/props/floor_wood.mdl",
        color = "#78350f"
    },
    ["floor_marble"] = {
        name = "Polished Italian Marble Tile",
        category = "structure",
        price = 85,
        width = 1, height: 1,
        icon = "🏛️",
        model = "models/props/floor_marble.mdl",
        color = "#f8fafc"
    },

    -- Furniture
    ["sofa_leather"] = {
        name = "Italian Leather Sectional Sofa",
        category = "furniture",
        price = 650,
        width = 3, height = 2,
        icon = "🛋️",
        model = "models/props/sofa.mdl",
        color = "#1e293b",
        comfortBonus = 15
    },
    ["chair_dining_wood"] = {
        name = "Handcrafted Oak Dining Chair (Slide-Out Seating)",
        category = "furniture",
        price = 120,
        width = 1, height = 1,
        icon = "🪑",
        model = "models/props/dining_chair.mdl",
        color = "#854d0e",
        maxHealth = 250,
        isChair = true,
        isInteractive = true,
        action = "SIT_CHAIR",
        slideDistance = 0.6,
        description = "Solid oak dining chair with smooth slide-out and tuck-in animation for sitting at tables."
    },
    ["chair_office_executive"] = {
        name = "Executive Ergonomic Swivel Chair (Slide-Out Seating)",
        category = "furniture",
        price = 280,
        width = 1, height = 1,
        icon = "🪑",
        model = "models/props/office_chair.mdl",
        color = "#0f172a",
        maxHealth = 300,
        isChair = true,
        isInteractive = true,
        action = "SIT_CHAIR",
        slideDistance = 0.7,
        description = "High-back ergonomic leather swivel chair with smooth glide castor animation for desks."
    },
    ["chair_kitchen_barstool"] = {
        name = "Industrial Counter Swivel Barstool",
        category = "furniture",
        price = 95,
        width = 1, height = 1,
        icon = "🪑",
        model = "models/props/barstool.mdl",
        color = "#713f12",
        maxHealth = 200,
        isChair = true,
        isInteractive = true,
        action = "SIT_CHAIR",
        slideDistance = 0.5,
        description = "Solid walnut barstool with 360-degree swivel and slide-out clearance."
    },
    ["bed_queen"] = {
        name = "Queen Plush Memory Foam Bed",
        category = "furniture",
        price = 850,
        width = 2, height = 3,
        icon = "🛏️",
        model = "models/props/bed.mdl",
        color = "#0284c7",
        isInteractive = true,
        action = "REST_PLAYER"
    },
    ["dining_table"] = {
        name = "Solid Mahogany Dining Table",
        category = "furniture",
        price = 400,
        width = 3, height = 2,
        icon = "🪑",
        model = "models/props/table.mdl",
        color = "#451a03"
    },
    ["coffee_table"] = {
        name = "Glass Minimalist Coffee Table",
        category = "furniture",
        price = 150,
        width = 2, height: 1,
        icon = "☕",
        model = "models/props/coffee_table.mdl",
        color = "#0f172a"
    },
    ["flatscreen_tv"] = {
        name = "75\" 4K OLED Smart TV",
        category = "furniture",
        price = 1200,
        width = 2, height: 1,
        icon = "📺",
        model = "models/props/tv.mdl",
        color = "#000000",
        isInteractive = true,
        action = "TOGGLE_TV"
    },

    -- Kitchen & Food
    ["refrigerator"] = {
        name = "Commercial Double-Door Fridge",
        category = "kitchen",
        price = 950,
        width = 2, height: 2,
        icon = "🧊",
        model = "models/props/fridge.mdl",
        color = "#94a3b8",
        isInteractive = true,
        action = "OPEN_FRIDGE_STORAGE"
    },
    ["stove_oven"] = {
        name = "Commercial Gas Range Stove & Oven (1 Per House)",
        category = "kitchen",
        price = 750,
        width = 2, height = 2,
        icon = "🍳",
        model = "models/props/stove.mdl",
        color = "#334155",
        maxHealth = 600,
        maxPerProperty = 1,
        isInteractive = true,
        action = "OPEN_COOKING_STOVE",
        description = "Grid-locked 6-burner commercial gas stove and convection oven. Cook hot gourmet meals to fully restore hunger, thirst, health, and gain stamina buffs (Limit 1 per house)."
    },
    ["kitchen_counter"] = {
        name = "Granite Kitchen Island Counter",
        category = "kitchen",
        price = 300,
        width = 2, height: 1,
        icon = "🍽️",
        model = "models/props/counter.mdl",
        color = "#1e293b"
    },

    -- Production & Workbenches
    ["synth_lab_table"] = {
        name = "Laboratory Synthesis Reactor",
        category = "production",
        price = 2500,
        width = 3, height: 2,
        icon = "⚗️",
        model = "models/props/chem_station.mdl",
        color = "#581c87",
        isInteractive = true,
        action = "OPEN_SYNTH"
    },
    ["hydro_grow_pot"] = {
        name = "High-Yield Hydroponic Planter",
        category = "production",
        price = 350,
        width = 1, height: 1,
        icon = "🪴",
        model = "models/props/hydro_pot.mdl",
        color = "#15803d",
        isInteractive = true,
        action = "OPEN_BOTANY"
    },
    ["grow_lamp_ceiling"] = {
        name = "Full Spectrum UV Grow Lamp",
        category = "production",
        price = 450,
        width = 2, height = 1,
        icon = "💡",
        model = "models/props/grow_lamp.mdl",
        color = "#a855f7",
        growthMultiplier = 1.3
    },
    ["workbench_engineering"] = {
        name = "Precision Engineering Work Bench (1 Per House)",
        category = "production",
        price = 650,
        width = 2, height = 1,
        icon = "🔧",
        model = "models/props/engineering_workbench.mdl",
        color = "#0284c7",
        maxHealth = 1200,
        maxPerProperty = 1,
        isInteractive = true,
        action = "OPEN_WORKBENCH",
        description = "Grid-locked heavy engineering bench for upgrading lock hardware, calibrating multimeters & cordless drills, and tuning security transmitters (Limit 1 per house)."
    },
    ["crafting_bench_master"] = {
        name = "Heavy Fabrication Crafting Bench (1 Per House)",
        category = "production",
        price = 500,
        width = 2, height = 1,
        icon = "🔨",
        model = "models/props/fabrication_craftbench.mdl",
        color = "#d97706",
        maxHealth = 1000,
        maxPerProperty = 1,
        isInteractive = true,
        action = "OPEN_CRAFTING_BENCH",
        description = "Grid-locked fabrication station for assembling prop barricades, lockpick sets, CCTV camera kits, and gym weight plates (Limit 1 per house)."
    },
    ["gunsmith_workbench"] = {
        name = "Precision Gunsmith Workbench",
        category = "production",
        price = 1800,
        width = 3, height: 2,
        icon = "🛠️",
        model = "models/props/workbench.mdl",
        color = "#713f12",
        isInteractive = true,
        action = "OPEN_CRAFTING"
    },

    -- Security & Storage
    ["secure_vault_safe"] = {
        name = "Heavy Reinforced Titanium Safe",
        category = "security",
        price = 1500,
        width = 2, height: 2,
        icon = "🗄️",
        model = "models/props/safe.mdl",
        color = "#0f172a",
        isInteractive = true,
        action = "OPEN_VAULT_STORAGE"
    },
    ["cctv_security_station"] = {
        name = "CCTV Security Camera Monitor",
        category = "security",
        price = 1100,
        width = 2, height: 1,
        icon = "📹",
        model = "models/props/cctv_desk.mdl",
        color = "#0369a1",
        isInteractive = true,
        action = "VIEW_CCTV"
    },
    ["weapon_rack"] = {
        name = "Wall-Mounted Tactical Weapon Rack",
        category = "security",
        price = 600,
        width = 2, height: 1,
        icon = "⚔️",
        model = "models/props/gun_rack.mdl",
        color = "#1e293b",
        isInteractive = true,
        action = "OPEN_ARMORY"
    },

    -- Lighting & Decor
    ["neon_strip_cyan"] = {
        name = "Cyberpunk Cyan Neon Strip",
        category = "lighting",
        price = 180,
        width = 2, height: 1,
        icon = "💡",
        model = "models/props/neon_cyan.mdl",
        color = "#00f2fe"
    },
    ["modern_floor_lamp"] = {
        name = "Arc Brass Floor Lamp",
        category = "lighting",
        price = 140,
        width = 1, height: 1,
        icon = "🏮",
        model = "models/props/floor_lamp.mdl",
        color = "#f59e0b"
    },
    ["indoor_palm"] = {
        name = "Potted Paradise Palm Plant",
        category = "lighting",
        price = 95,
        width = 1, height: 1,
        icon = "🌴",
        model = "models/props/palm.mdl",
        color = "#10b981"
    },
    ["modern_rug"] = {
        name = "Geometric Plush Floor Rug",
        category = "lighting",
        price = 120,
        width = 3, height: 2,
        icon = "🧶",
        model = "models/props/rug.mdl",
        color = "#6366f1"
    }
}
