"use client";

import { useState } from "react";
import { 
  Swords, ShieldAlert, Trophy, ChevronRight, Zap, Target, Gamepad2, Landmark, Compass
} from "lucide-react";

// Addon database structures loaded dynamically in UI
const coaClasses = [
  {
    id: "felsworn",
    name: "Felsworn",
    resource: "Felfury",
    maxResource: 100,
    role: "DPS / Tank",
    desc: "A demonic warrior harnessing fel energy to destroy enemies as a mobile shadowflame caster, a high-speed twin-blade slayer, or a chaotic evasion tank.",
    specs: [
      {
        id: "infernal",
        name: "Infernal (Caster DPS)",
        rotation: [
          "1. APPLY Voidblaze DoT (refresh at 2s left)",
          "2. BUILD Felfury with Chaos Incursion",
          "3. REACT to Infernal Magicks proc (instant Engulf)",
          "4. SPEND at 50 with Fel Prison (if utility/burst needed)",
          "5. SPEND at 80+ with Engulf",
        ],
        abilities: [
          { name: "Voidblaze", type: "debuff", icon: "🔥", desc: "Burns target for Shadowflame damage over 12s, generating 5 Felfury per tick.", hint: "Keep Voidblaze DoT ticking at all times." },
          { name: "Chaos Incursion", type: "generator", icon: "✨", desc: "Ranged fel blast. Generates 15 Felfury. Can be cast while moving.", hint: "Cast on the move to generate Felfury." },
          { name: "Infernal Magicks", type: "proc", icon: "⚡", desc: "Chaos Incursion crits make your next Engulf instant and cost 30 less Felfury.", hint: "Cast Engulf instantly now!" },
          { name: "Fel Prison", type: "spender", icon: "🕸️", desc: "Roots the target and deals Shadowflame damage. Costs 50 Felfury.", hint: "Lock down enemies and deal quick burst." },
          { name: "Engulf", type: "spender", icon: "☄️", desc: "Unleash a massive fire blast on the target. Costs 80 Felfury.", hint: "Massive single-target finisher. Don't cap Felfury." },
        ]
      },
      {
        id: "slayer",
        name: "Slayer (Melee DPS)",
        rotation: [
          "1. Gap close using Fel Hoof Charge to initiate combat.",
          "2. Spend Felfury at 40 with Voidblaze to stack Infernal Alacrity.",
          "3. Maintain 5 stacks of Infernal Alacrity for max attack speed.",
          "4. Generate Felfury using Fell Strike slash combos.",
        ],
        abilities: [
          { name: "Infernal Alacrity", type: "buff", icon: "⚡", desc: "Attack speed increased by 8% per stack (max 5). Generated by Voidblaze.", hint: "Maintain stacks: keep at 5 stacks at all times." },
          { name: "Fel Hoof Charge", type: "cooldown", icon: "🏇", desc: "Charge through targets, striking them down. Generates 25 Felfury.", hint: "Use to initiate and get instant Felfury." },
          { name: "Voidblaze", type: "spender", icon: "🔥", desc: "Imbues weapons with void fire. Costs 40 Felfury. Generates Alacrity.", hint: "Maintain speed buffs using this." },
          { name: "Fell Strike", type: "generator", icon: "⚔️", desc: "Dual twin blades slash combo. Generates 20 Felfury.", hint: "Spam to build Felfury." },
        ]
      }
    ]
  },
  {
    id: "witch_hunter",
    name: "Witch Hunter",
    resource: "Focus",
    maxResource: 100,
    role: "DPS (Ranged/Hybrid)",
    desc: "A shadowy monster hunter combining crossbow marksmanship with melee purging blades. Uses Focus to fuel precise shots and arcane-banishing abilities.",
    specs: [
      {
        id: "inquisitor",
        name: "Inquisitor (Ranged DPS)",
        rotation: [
          "1. Mark target before pulling to increase all damage.",
          "2. Keep Purging Shot on cooldown to dispel magic shields.",
          "3. Generate Focus using Steady Shot.",
          "4. Spend Focus on Shadow-infused Arrow combos.",
        ],
        abilities: [
          { name: "Mark Target", type: "debuff", icon: "🎯", desc: "Places a mark of execution on the target, increasing all damage dealt to it by 15%.", hint: "Apply before starting combat." },
          { name: "Purging Shot", type: "cooldown", icon: "🏹", desc: "Removes 1 beneficial Magic effect from the target and deals Shadow damage.", hint: "Use immediately when target gains magic shields." },
          { name: "Steady Shot", type: "generator", icon: "⚡", desc: "Steady ranged cast. Generates 15 Focus.", hint: "Primary Focus builder." },
          { name: "Shadow Shot", type: "spender", icon: "☄️", desc: "Empowers your arrow with shadow magic, dealing high burst. Costs 45 Focus.", hint: "Primary Focus spender." }
        ]
      }
    ]
  },
  {
    id: "necromancer",
    name: "Necromancer",
    resource: "Runic Power",
    maxResource: 100,
    role: "DPS / Support",
    desc: "A master of death magic who raises undead minions and spreads corrupting diseases. Your army of undead makes soloing elites trivial.",
    specs: [
      {
        id: "reanimation",
        name: "Reanimation (Pet DPS)",
        rotation: [
          "1. Summon Abomination to tank incoming mobs.",
          "2. Apply Blood Plague and Frost Fever via Outbreak.",
          "3. Spam Death Coil to dump Runic Power.",
          "4. Generate resource using Plague Strike.",
        ],
        abilities: [
          { name: "Blood Plague", type: "debuff", icon: "🩸", desc: "Dark disease that deals physical damage over 15s and heals your pets.", hint: "Keep applied on primary targets." },
          { name: "Frost Fever", type: "debuff", icon: "❄️", desc: "Deals frost damage and reduces target attack speed by 14% over 15s.", hint: "Keep applied on targets to decrease tank damage." },
          { name: "Abomination", type: "cooldown", icon: "🧟", desc: "Summons a hulking monstrosity to tank and cleave. Lasts 30s.", hint: "Use on pack pulls and elite bosses." },
          { name: "Death Coil", type: "spender", icon: "💀", desc: "Fires unholy energy dealing shadow damage or healing your undead pets.", hint: "Primary RP dump. Use to keep pets alive." },
        ]
      }
    ]
  },
  {
    id: "reaper",
    name: "Reaper",
    resource: "Reaped Souls",
    maxResource: 10,
    role: "DPS / Tank",
    desc: "A grim harvester of souls who wields dual scythes or a massive polearm to siphon health and essence from their victims.",
    specs: [
      {
        id: "harvest",
        name: "Harvest (Melee DPS)",
        rotation: [
          "1. Apply Reaper's Mark to siphon passive health.",
          "2. Generate Reaped Souls using Scythe Slash.",
          "3. Spend Reaped Souls at 5+ stacks to trigger Soul Ward.",
          "4. Execute low-health enemies using Reap Essence.",
        ],
        abilities: [
          { name: "Reaper's Mark", type: "debuff", icon: "💀", desc: "Marks the target's soul, transferring 10% of all damage dealt as self-healing.", hint: "Keep applied for passive health sustain." },
          { name: "Scythe Slash", type: "generator", icon: "⚔️", desc: "Sweeps twin scythes through targets. Generates 1 Reaped Soul per target hit.", hint: "Use to build soul charges." },
          { name: "Soul Ward", type: "buff", icon: "🛡️", desc: "Consumes 5 Reaped Souls to generate an absorption shield lasting 10 seconds.", hint: "Use to block heavy magic spell bursts." },
          { name: "Reap Essence", type: "spender", icon: "⚡", desc: "Executes target under 20% health. Costs 3 Reaped Souls.", hint: "Use as a finisher." }
        ]
      }
    ]
  }
];

const coaDungeons = [
  {
    name: "The Deadmines",
    levels: "Levels 17 - 22",
    drops: [
      { item: "Cruel Barb", type: "Melee Sword", boss: "Edwin VanCleef" },
      { item: "Blackened Defias Armor", type: "Leather Chestpiece", boss: "Edwin VanCleef" }
    ]
  },
  {
    name: "Wailing Caverns",
    levels: "Levels 15 - 22",
    drops: [
      { item: "Crescent Staff", type: "Caster Staff", boss: "Leaders of the Fang Quest" }
    ]
  },
  {
    name: "Shadowfang Keep",
    levels: "Levels 20 - 26",
    drops: [
      { item: "Butcher's Slicer", type: "Melee Axe", boss: "Razorclaw the Butcher" },
      { item: "Meteor Shard", type: "Caster Dagger", boss: "Archmage Arugal" },
      { item: "Commander's Crest", type: "Shield", boss: "Commander Springvale" }
    ]
  },
  {
    name: "Scarlet Monastery",
    levels: "Levels 30 - 40",
    drops: [
      { item: "Ravager", type: "2H Axe", boss: "Herod (Armory)" },
      { item: "Illusionary Rod", type: "Caster Staff", boss: "Arcanist Doan (Library)" },
      { item: "Triune Amulet", type: "Necklace", boss: "High Inquisitor Whitemane" },
      { item: "Herod's Shoulder", type: "Mail Shoulders", boss: "Herod (Armory)" }
    ]
  },
  {
    name: "Zul'Farrak",
    levels: "Levels 43 - 48",
    drops: [
      { item: "Sul'thraze the Lasher", type: "Epic 2H Sword", boss: "Combine Sang'thraze & Jang'thraze" }
    ]
  },
  {
    name: "Blackrock Depths (BRD)",
    levels: "Levels 52 - 60",
    drops: [
      { item: "Hand of Justice", type: "Physical Trinket", boss: "General Angerforge" },
      { item: "Ironfoe", type: "1H Mace (Proc)", boss: "Emperor Dagran Thaurissan" },
      { item: "Savage Gladiator Chain", type: "Mail Chest", boss: "Ring of Law Arena" },
      { item: "Void-Injected Blade", type: "Felsworn Sword", boss: "General Angerforge" }
    ]
  }
];

const ascensionGearing = [
  {
    phase: "Phase 1: Entry Level Gearing",
    desc: "Replace leveling greens with ilvl 58-60 dungeon blues to qualify for Heroics.",
    tips: [
      "Orgrimmar Call Board: Pick up daily call board quests for scaling loot caches.",
      "Marks of Triumph: Complete normal dungeons using the Dungeon Finder to earn emblem tokens."
    ]
  },
  {
    phase: "Phase 2: Heroic Dungeons (ilvl 61+)",
    desc: "Queue Heroic random dungeons. This is where stat optimization starts.",
    tips: [
      "Badges of Justice: Gather emblems from every heroic dungeon boss drop.",
      "G'eras (Shattrath): Spend badges on high-tier stat relics, trinkets, and chest pieces."
    ]
  },
  {
    phase: "Phase 3: Mythic Keys (ilvl 64+)",
    desc: "Complete Mythic keystones to scale item level and challenge modifiers.",
    tips: [
      "Ascension Marks: Clear daily mythic objectives to redeem token rewards."
    ]
  }
];

export default function CoADashboard() {
  const [selectedClass, setSelectedClass] = useState(coaClasses[0]);
  const [selectedSpec, setSelectedSpec] = useState(coaClasses[0].specs[0]);
  const [activeTab, setActiveTab] = useState<"rotation" | "auras" | "dungeons">("rotation");

  const handleClassSelect = (cls: typeof coaClasses[0]) => {
    setSelectedClass(cls);
    setSelectedSpec(cls.specs[0]);
  };

  return (
    <div className="p-8 max-w-6xl mx-auto space-y-8">
      {/* Title Header */}
      <header className="flex flex-col md:flex-row justify-between md:items-center border-b border-border/50 pb-6 gap-4">
        <div>
          <span className="text-[10px] uppercase font-extrabold text-primary tracking-widest block mb-1">Project Ascension</span>
          <h1 className="text-3xl font-extrabold flex items-center gap-2 tracking-tight">
            <Swords className="w-8 h-8 text-primary animate-pulse" />
            Conquest of Azeroth Addon Manager
          </h1>
          <p className="text-muted-foreground text-sm mt-1">
            Official companion database for Conquest of Azeroth custom classes, leveling guides, and boss loot tables.
          </p>
        </div>
        <div className="flex gap-3">
          <span className="px-3.5 py-1.5 bg-indigo-500/10 border border-indigo-500/30 text-indigo-400 text-xs rounded-xl font-bold flex items-center gap-1.5">
            <Compass className="w-4 h-4 animate-spin text-indigo-400" />
            Ascension Realm Status: Active
          </span>
        </div>
      </header>

      {/* Class Overview Cards Banner */}
      <section className="bg-gradient-to-r from-purple-950/20 via-slate-900/50 to-indigo-950/20 border border-border/50 rounded-3xl p-6 relative overflow-hidden">
        <div className="absolute inset-0 bg-[linear-gradient(to_bottom,rgba(99,102,241,0.02)_1px,transparent_1px),linear-gradient(to_right,rgba(99,102,241,0.02)_1px,transparent_1px)] bg-[size:24px_24px] pointer-events-none" />
        <div className="relative z-10 max-w-2xl">
          <span className="text-[10px] uppercase font-bold text-primary tracking-widest block mb-2">Class Overview</span>
          <h2 className="text-xl font-extrabold text-white">{selectedClass.name} — {selectedClass.role}</h2>
          <p className="text-xs text-gray-400 mt-2 leading-relaxed">{selectedClass.desc}</p>
        </div>
      </section>

      {/* Main Grid */}
      <div className="grid md:grid-cols-4 gap-6 items-start">
        {/* Class Selection Left Column */}
        <div className="bg-secondary/15 border border-border/50 rounded-2xl p-5 space-y-4">
          <h3 className="text-xs uppercase font-extrabold text-muted-foreground tracking-wider mb-2">Select CoA Class</h3>
          <div className="flex flex-col gap-2">
            {coaClasses.map((cls) => {
              const isActive = selectedClass.id === cls.id;
              return (
                <button
                  key={cls.id}
                  onClick={() => handleClassSelect(cls)}
                  className={`w-full text-left p-3.5 rounded-xl border flex justify-between items-center transition-all ${
                    isActive 
                      ? "bg-primary/10 border-primary text-white font-bold" 
                      : "bg-black/10 border-border/30 text-gray-400 hover:text-white"
                  }`}
                >
                  <span>{cls.name}</span>
                  <ChevronRight className={`w-4 h-4 opacity-50 transition-transform ${isActive ? "rotate-90 text-primary" : ""}`} />
                </button>
              );
            })}
          </div>

          <div className="border-t border-border/30 pt-4 space-y-3">
            <span className="text-xs uppercase font-extrabold text-muted-foreground tracking-wider block">Specializations</span>
            <div className="flex flex-wrap gap-2">
              {selectedClass.specs.map((spec) => (
                <button
                  key={spec.id}
                  onClick={() => setSelectedSpec(spec)}
                  className={`px-3 py-1.5 rounded-lg border text-xs font-semibold transition-all ${
                    selectedSpec.id === spec.id
                      ? "bg-[#6366f1]/20 border-[#6366f1] text-[#6366f1]"
                      : "bg-black/10 border-border/30 text-gray-400 hover:text-white"
                  }`}
                >
                  {spec.name}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Spec Content & Tabs (Right Column) */}
        <div className="md:col-span-3 space-y-6">
          {/* Tabs header */}
          <div className="flex gap-2 border-b border-border/50 pb-2">
            <button
              onClick={() => setActiveTab("rotation")}
              className={`pb-2.5 px-4 font-bold text-sm border-b-2 transition-all flex items-center gap-1.5 ${
                activeTab === "rotation" ? "border-primary text-primary" : "border-transparent text-gray-500 hover:text-white"
              }`}
            >
              <Target className="w-4 h-4" /> Rotation Priorities
            </button>
            <button
              onClick={() => setActiveTab("auras")}
              className={`pb-2.5 px-4 font-bold text-sm border-b-2 transition-all flex items-center gap-1.5 ${
                activeTab === "auras" ? "border-primary text-primary" : "border-transparent text-gray-500 hover:text-white"
              }`}
            >
              <Zap className="w-4 h-4" /> Buffs & Debuffs
            </button>
            <button
              onClick={() => setActiveTab("dungeons")}
              className={`pb-2.5 px-4 font-bold text-sm border-b-2 transition-all flex items-center gap-1.5 ${
                activeTab === "dungeons" ? "border-primary text-primary" : "border-transparent text-gray-500 hover:text-white"
              }`}
            >
              <Trophy className="w-4 h-4" /> Dungeons & Drops
            </button>
          </div>

          {/* TAB 1: Rotation */}
          {activeTab === "rotation" && (
            <div className="space-y-6">
              {/* Rotation Priority List */}
              <div className="bg-[#0e1422]/60 border border-border/50 rounded-2xl p-6 space-y-4">
                <h3 className="text-base font-bold flex items-center gap-1.5 text-primary">
                  <Gamepad2 className="w-5 h-5 text-amber-500" />
                  Suggested Attack Priorities
                </h3>
                <div className="space-y-3 font-mono text-xs">
                  {selectedSpec.rotation.map((item, idx) => (
                    <div key={idx} className="flex gap-3 bg-black/25 p-3 rounded-xl border border-border/30">
                      <span className="text-amber-500 font-extrabold">▶</span>
                      <span className="text-gray-300">{item}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Abilities list */}
              <div className="space-y-4">
                <h3 className="text-xs uppercase font-extrabold text-muted-foreground tracking-wider">Rotational Abilities & Details</h3>
                <div className="grid gap-3">
                  {selectedSpec.abilities.map((ab) => (
                    <div key={ab.name} className="bg-secondary/10 border border-border/40 rounded-xl p-4 flex gap-4 items-center">
                      <div className="w-10 h-10 rounded-xl bg-black/40 border border-border flex items-center justify-center text-lg select-none">
                        {ab.icon}
                      </div>
                      <div className="flex-grow">
                        <div className="flex items-center gap-2">
                          <h4 className="font-bold text-sm">{ab.name}</h4>
                          <span className={`text-[9px] uppercase px-2 py-0.5 rounded font-bold ${
                            ab.type === 'debuff' ? 'bg-rose-500/10 text-rose-400 border border-rose-500/20' :
                            ab.type === 'buff' ? 'bg-green-500/10 text-green-400 border border-green-500/20' :
                            ab.type === 'generator' ? 'bg-blue-500/10 text-blue-400 border border-blue-500/20' :
                            ab.type === 'spender' ? 'bg-orange-500/10 text-orange-400 border border-orange-500/20' :
                            'bg-purple-500/10 text-purple-400 border border-purple-500/20'
                          }`}>
                            {ab.type}
                          </span>
                        </div>
                        <p className="text-xs text-gray-400 mt-1">{ab.desc}</p>
                        <p className="text-[10px] text-amber-500/90 italic mt-0.5">Note: {ab.hint}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* TAB 2: Auras */}
          {activeTab === "auras" && (
            <div className="space-y-6">
              <div className="bg-[#0e1422]/60 border border-border/50 rounded-2xl p-6">
                <h3 className="text-base font-bold flex items-center gap-2 mb-4">
                  <ShieldAlert className="w-5 h-5 text-rose-500" />
                  Active Auras to Maintain
                </h3>

                <div className="grid md:grid-cols-2 gap-4">
                  {/* Buffs Column */}
                  <div className="space-y-3">
                    <h4 className="text-xs uppercase font-extrabold text-green-400 tracking-wider">Player Buffs</h4>
                    {selectedSpec.abilities.filter(a => a.type === 'buff' || a.type === 'proc').map(ab => (
                      <div key={ab.name} className="bg-green-500/5 border border-green-500/20 rounded-xl p-3.5 space-y-2">
                        <div className="flex items-center gap-2">
                          <span className="text-lg">{ab.icon}</span>
                          <span className="font-bold text-sm text-green-400">{ab.name}</span>
                        </div>
                        <p className="text-xs text-gray-400 leading-relaxed">{ab.desc}</p>
                      </div>
                    ))}
                    {selectedSpec.abilities.filter(a => a.type === 'buff' || a.type === 'proc').length === 0 && (
                      <p className="text-xs text-gray-500 italic">No self buffs tracked for this spec.</p>
                    )}
                  </div>

                  {/* Debuffs Column */}
                  <div className="space-y-3">
                    <h4 className="text-xs uppercase font-extrabold text-rose-400 tracking-wider">Target Debuffs</h4>
                    {selectedSpec.abilities.filter(a => a.type === 'debuff').map(ab => (
                      <div key={ab.name} className="bg-rose-500/5 border border-rose-500/20 rounded-xl p-3.5 space-y-2">
                        <div className="flex items-center gap-2">
                          <span className="text-lg">{ab.icon}</span>
                          <span className="font-bold text-sm text-rose-400">{ab.name}</span>
                        </div>
                        <p className="text-xs text-gray-400 leading-relaxed">{ab.desc}</p>
                      </div>
                    ))}
                    {selectedSpec.abilities.filter(a => a.type === 'debuff').length === 0 && (
                      <p className="text-xs text-gray-500 italic">No target debuffs tracked for this spec.</p>
                    )}
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* TAB 3: Dungeons & Drops */}
          {activeTab === "dungeons" && (
            <div className="space-y-6">
              {/* Project Ascension Gearing Stages */}
              <div className="bg-[#0e1422]/60 border border-border/50 rounded-2xl p-6 space-y-4">
                <h3 className="text-base font-bold flex items-center gap-1.5 text-primary">
                  <Landmark className="w-5 h-5 text-amber-500" />
                  Ascension Endgame Gearing Guide
                </h3>
                <div className="grid md:grid-cols-3 gap-4">
                  {ascensionGearing.map((stage, idx) => (
                    <div key={idx} className="bg-black/25 border border-border/30 rounded-xl p-4 space-y-2 flex flex-col justify-between">
                      <div>
                        <h4 className="font-bold text-xs text-indigo-400">{stage.phase}</h4>
                        <p className="text-[10px] text-gray-400 mt-1 leading-relaxed">{stage.desc}</p>
                      </div>
                      <ul className="text-[9px] text-gray-500 list-disc list-inside mt-2 space-y-1">
                        {stage.tips.map((tip, ti) => (
                          <li key={ti}>{tip}</li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>
              </div>

              {/* Lower Level Dungeon drops */}
              <div className="space-y-4">
                <h3 className="text-xs uppercase font-extrabold text-gray-400 tracking-wider">CoA Dungeon Loot Tables</h3>
                <div className="grid md:grid-cols-2 gap-4">
                  {coaDungeons.map((dung) => (
                    <div key={dung.name} className="bg-[#0e1422]/60 border border-border/50 rounded-2xl p-5 space-y-4">
                      <div className="flex justify-between items-center border-b border-border/30 pb-3">
                        <div>
                          <h4 className="font-bold text-base text-white">{dung.name}</h4>
                          <span className="text-xs text-gray-500">{dung.levels}</span>
                        </div>
                        <span className="px-2.5 py-1 bg-primary/10 border border-primary/20 text-primary text-[10px] font-bold rounded-lg uppercase">
                          Dungeon
                        </span>
                      </div>

                      <div className="space-y-2">
                        <span className="text-[10px] uppercase font-bold text-muted-foreground tracking-wider">Key Drops & Loot</span>
                        <div className="space-y-2 font-mono text-[11px]">
                          {dung.drops.map((dr) => (
                            <div key={dr.item} className="flex justify-between bg-black/25 p-2 rounded-lg border border-border/20">
                              <div>
                                <div className="font-bold text-amber-400">💍 {dr.item}</div>
                                <div className="text-[9px] text-gray-500">{dr.type}</div>
                              </div>
                              <span className="text-gray-400 self-center text-[10px]">{dr.boss}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
